version: '3.1'

services: 
  conexion:
    image: postgres:16.1
    container_name: conexion
    restart: always
    environment: 
      POSTGRES_DB: elsolnec
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
